// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth.proto

package grpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	_go "github.com/sweetloveinyourheart/sweet-reel/proto/code/auth/go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "com.sweetloveinyourheart.srl.auth.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceOAuthLoginProcedure is the fully-qualified name of the AuthService's OAuthLogin RPC.
	AuthServiceOAuthLoginProcedure = "/com.sweetloveinyourheart.srl.auth.AuthService/OAuthLogin"
	// AuthServiceRefreshTokenProcedure is the fully-qualified name of the AuthService's RefreshToken
	// RPC.
	AuthServiceRefreshTokenProcedure = "/com.sweetloveinyourheart.srl.auth.AuthService/RefreshToken"
)

// AuthServiceClient is a client for the com.sweetloveinyourheart.srl.auth.AuthService service.
type AuthServiceClient interface {
	// Handles OAuth login with external providers (Google, GitHub, etc.)
	OAuthLogin(context.Context, *connect.Request[_go.OAuthLoginRequest]) (*connect.Response[_go.OAuthLoginResponse], error)
	// Optionally, validate or refresh tokens later.
	RefreshToken(context.Context, *connect.Request[_go.RefreshTokenRequest]) (*connect.Response[_go.RefreshTokenResponse], error)
}

// NewAuthServiceClient constructs a client for the com.sweetloveinyourheart.srl.auth.AuthService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := _go.File_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		oAuthLogin: connect.NewClient[_go.OAuthLoginRequest, _go.OAuthLoginResponse](
			httpClient,
			baseURL+AuthServiceOAuthLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("OAuthLogin")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[_go.RefreshTokenRequest, _go.RefreshTokenResponse](
			httpClient,
			baseURL+AuthServiceRefreshTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	oAuthLogin   *connect.Client[_go.OAuthLoginRequest, _go.OAuthLoginResponse]
	refreshToken *connect.Client[_go.RefreshTokenRequest, _go.RefreshTokenResponse]
}

// OAuthLogin calls com.sweetloveinyourheart.srl.auth.AuthService.OAuthLogin.
func (c *authServiceClient) OAuthLogin(ctx context.Context, req *connect.Request[_go.OAuthLoginRequest]) (*connect.Response[_go.OAuthLoginResponse], error) {
	return c.oAuthLogin.CallUnary(ctx, req)
}

// RefreshToken calls com.sweetloveinyourheart.srl.auth.AuthService.RefreshToken.
func (c *authServiceClient) RefreshToken(ctx context.Context, req *connect.Request[_go.RefreshTokenRequest]) (*connect.Response[_go.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the com.sweetloveinyourheart.srl.auth.AuthService
// service.
type AuthServiceHandler interface {
	// Handles OAuth login with external providers (Google, GitHub, etc.)
	OAuthLogin(context.Context, *connect.Request[_go.OAuthLoginRequest]) (*connect.Response[_go.OAuthLoginResponse], error)
	// Optionally, validate or refresh tokens later.
	RefreshToken(context.Context, *connect.Request[_go.RefreshTokenRequest]) (*connect.Response[_go.RefreshTokenResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := _go.File_auth_proto.Services().ByName("AuthService").Methods()
	authServiceOAuthLoginHandler := connect.NewUnaryHandler(
		AuthServiceOAuthLoginProcedure,
		svc.OAuthLogin,
		connect.WithSchema(authServiceMethods.ByName("OAuthLogin")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshTokenHandler := connect.NewUnaryHandler(
		AuthServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/com.sweetloveinyourheart.srl.auth.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceOAuthLoginProcedure:
			authServiceOAuthLoginHandler.ServeHTTP(w, r)
		case AuthServiceRefreshTokenProcedure:
			authServiceRefreshTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) OAuthLogin(context.Context, *connect.Request[_go.OAuthLoginRequest]) (*connect.Response[_go.OAuthLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("com.sweetloveinyourheart.srl.auth.AuthService.OAuthLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) RefreshToken(context.Context, *connect.Request[_go.RefreshTokenRequest]) (*connect.Response[_go.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("com.sweetloveinyourheart.srl.auth.AuthService.RefreshToken is not implemented"))
}
