linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - paramTypeCombine
      - hugeParam
  gocyclo:
    min-complexity: 15
  godox:
    # Report any comments starting with keywords, this is useful for TODO or FIXME comments that
    # might be left in the code accidentally and should be resolved before merging.
    # Default: ["TODO", "BUG", "FIXME"]
    keywords:
      - TODO
      - BUG
      - FIXME
      - OPTIMIZE # marks code that should be optimized before merging
      - HACK # marks hack-around that should be removed before merging
      - blaarg
  goimports:
    local-prefixes: github.com/sweetloveinyourheart/exploding-kittens
  stylecheck:
    checks: ["all", "-ST1003"]
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  staticcheck:
    checks:
      - all # do all static checks
      - '-SA1019' # allow for use of xerrors

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
 # presets:
 #   - unused
  enable:
    - bodyclose
    # depguard
    #    - dogsled
    #    - dupl
    - errcheck
    #    - exportloopref
    #    - funlen
    #    - gochecknoinits
    #    - goconst
    #    - gocritic
    #    - gocyclo
    - godox
    - gofmt
    #    - goimports
    #    - gomnd
    - goprintffuncname
    #    - gosec
    - gosimple
    - govet
    - ineffassign
    #    - lll
    #    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - staticcheck
    #    - structcheck
    #    - stylecheck
    - typecheck
    - unconvert
    #    - unparam
    - unused
  #    - whitespace

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - revive
  # - wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - godox
    - path: tests/gherkin
      linters:
        - godox
    - path: _generated\.go
      linters:
        - unused
    # These errors should be addressed in the chat system
    - path: chat_system
      linters:
        - nakedret
        - unused
        - errcheck
        - gofmt
    - path: itest
      linters:
        - nakedret
        - unused
        - errcheck
  exclude-dirs:
    - .gobincache
run:
  timeout: 5m
