- name: user
  shortName: Run as user service
  long: ""
  service:
    ports: []
    healthCheckPorts:
    - name: healthcheck-grpc
      wireProtocol: tcp
      protocol: grpc
      public: false
      defaultRoutes: []
      flagName: healthcheck-port
      flagUsage: Port to listen on for services that support a health check
      configName: healthcheck.port
      defaultValue: 5051
      env:
      - SWEET_REEL_HEALTHCHECK_PORT
    - name: healthcheck-web
      wireProtocol: tcp
      protocol: http
      public: false
      defaultRoutes:
      - /healthz
      - /readyz
      flagName: healthcheck-web-port
      flagUsage: Port to listen on for services that support a health check
      configName: healthcheck.web.port
      defaultValue: 5052
      env:
      - SWEET_REEL_HEALTHCHECK_WEB_PORT
    defaultDatabaseName: ""
  config:
  - name: db-migrations-url
    usage: Database connection migrations URL
    default: ""
    valueType: string
    path: user.db.migrations.url
    env:
    - USER_DB_MIGRATIONS_URL
  - name: db-postgres-connection-max-idletime
    usage: Max connection idle time in seconds
    default: 180
    valueType: int64
    path: user.db.postgres.max_idletime
    env:
    - USER_DB_POSTGRES_CONNECTION_MAX_IDLETIME
  - name: db-postgres-connection-max-lifetime
    usage: Max connection lifetime in seconds
    default: 300
    valueType: int64
    path: user.db.postgres.max_lifetime
    env:
    - USER_DB_POSTGRES_CONNECTION_MAX_LIFETIME
  - name: db-postgres-max-idle-connections
    usage: Maximum number of idle connections
    default: 50
    valueType: int64
    path: user.db.postgres.max_idle_connections
    env:
    - USER_DB_POSTGRES_MAX_IDLE_CONNECTIONS
  - name: db-postgres-max-open-connections
    usage: Maximum number of connections
    default: 500
    valueType: int64
    path: user.db.postgres.max_open_connections
    env:
    - USER_DB_POSTGRES_MAX_OPEN_CONNECTIONS
  - name: db-postgres-timeout
    usage: Timeout for postgres connection
    default: 60
    valueType: int64
    path: user.db.postgres.timeout
    env:
    - USER_DB_POSTGRES_TIMEOUT
  - name: db-read-url
    usage: Database connection readonly URL
    default: ""
    valueType: string
    path: user.db.read.url
    env:
    - USER_DB_READ_URL
  - name: db-url
    usage: Database connection URL
    default: ""
    valueType: string
    path: user.db.url
    env:
    - USER_DB_URL
  - name: grpc-port
    usage: GRPC Port to listen on
    default: 50060
    valueType: int64
    path: user.grpc.port
    env:
    - USER_GRPC_PORT
  - name: id
    usage: Unique identifier for this services
    default: ""
    valueType: string
    path: user.id
    env:
    - USER_ID
  - name: token-signing-key
    usage: Signing key used for service to service tokens
    default: ""
    valueType: string
    path: user.secrets.token_signing_key
    env:
    - USER_SECRETS_TOKEN_SIGNING_KEY
  - name: healthcheck-host
    usage: Host to listen on for services that support a health check
    default: localhost
    valueType: string
    path: healthcheck.host
    env:
    - SWEET_REEL_HEALTHCHECK_HOST
  - name: healthcheck-port
    usage: Port to listen on for services that support a health check
    default: 5051
    valueType: int
    path: healthcheck.port
    env:
    - SWEET_REEL_HEALTHCHECK_PORT
  - name: healthcheck-web-port
    usage: Port to listen on for services that support a health check
    default: 5052
    valueType: int
    path: healthcheck.web.port
    env:
    - SWEET_REEL_HEALTHCHECK_WEB_PORT
  - name: log-level
    usage: log level to use
    default: info
    valueType: string
    path: log.level
    env:
    - LOG_LEVEL
  - name: service
    usage: which service to run
    default: ""
    valueType: string
    path: service
    env:
    - SWEET_REEL_SERVICE
