services:
  phase_one_leader:
    image: ${ALPINE_CONTAINER_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME:-test}_phase_one_leader
    entrypoint: echo "Phase One Leader Launch - Distributes Components" && exit 0
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.7"

  sr_database:
    image: ${POSTGRES_CONTAINER_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME:-test}_database
    hostname: sr_database
    environment:
      "POSTGRES_DB": "postgres"
      "POSTGRES_USER": "root_admin"
      "POSTGRES_PASSWORD": "admin@123"
      "POSTGRES_MULTIPLE_DATABASES": "media_server:media_server;"
    ports:
      - "5432:5432"
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.31"
    volumes:
      - ./db/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    depends_on:
      phase_one_leader:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30

  sr_redis:
    hostname: redis
    image: ${REDIS_CONTAINER_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME:-test}-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      fs_test_net:
        ipv4_address: "172.16.244.51"
    depends_on:
      phase_one_leader:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 90s
      interval: 5s
      timeout: 4s
      retries: 30

networks:
  fs_test_net:
    name: fs_test_net
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: "172.16.244.0/23"