// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: video_management.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresignedUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	UploaderId    string                 `protobuf:"bytes,4,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignedUrlRequest) Reset() {
	*x = PresignedUrlRequest{}
	mi := &file_video_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignedUrlRequest) ProtoMessage() {}

func (x *PresignedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignedUrlRequest.ProtoReflect.Descriptor instead.
func (*PresignedUrlRequest) Descriptor() ([]byte, []int) {
	return file_video_management_proto_rawDescGZIP(), []int{0}
}

func (x *PresignedUrlRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PresignedUrlRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PresignedUrlRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PresignedUrlRequest) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *PresignedUrlRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type PresignedUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	PresignedUrl  string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignedUrlResponse) Reset() {
	*x = PresignedUrlResponse{}
	mi := &file_video_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignedUrlResponse) ProtoMessage() {}

func (x *PresignedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignedUrlResponse.ProtoReflect.Descriptor instead.
func (*PresignedUrlResponse) Descriptor() ([]byte, []int) {
	return file_video_management_proto_rawDescGZIP(), []int{1}
}

func (x *PresignedUrlResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *PresignedUrlResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *PresignedUrlResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type GetChannelVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelVideosRequest) Reset() {
	*x = GetChannelVideosRequest{}
	mi := &file_video_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelVideosRequest) ProtoMessage() {}

func (x *GetChannelVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelVideosRequest.ProtoReflect.Descriptor instead.
func (*GetChannelVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_management_proto_rawDescGZIP(), []int{2}
}

func (x *GetChannelVideosRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetChannelVideosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChannelVideosRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ChannelVideo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoTitle    string                 `protobuf:"bytes,2,opt,name=video_title,json=videoTitle,proto3" json:"video_title,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	TotalDuration int32                  `protobuf:"varint,4,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"`
	TotalView     int64                  `protobuf:"varint,5,opt,name=total_view,json=totalView,proto3" json:"total_view,omitempty"`
	ProcessedAt   int64                  `protobuf:"varint,6,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelVideo) Reset() {
	*x = ChannelVideo{}
	mi := &file_video_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelVideo) ProtoMessage() {}

func (x *ChannelVideo) ProtoReflect() protoreflect.Message {
	mi := &file_video_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelVideo.ProtoReflect.Descriptor instead.
func (*ChannelVideo) Descriptor() ([]byte, []int) {
	return file_video_management_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelVideo) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ChannelVideo) GetVideoTitle() string {
	if x != nil {
		return x.VideoTitle
	}
	return ""
}

func (x *ChannelVideo) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *ChannelVideo) GetTotalDuration() int32 {
	if x != nil {
		return x.TotalDuration
	}
	return 0
}

func (x *ChannelVideo) GetTotalView() int64 {
	if x != nil {
		return x.TotalView
	}
	return 0
}

func (x *ChannelVideo) GetProcessedAt() int64 {
	if x != nil {
		return x.ProcessedAt
	}
	return 0
}

type GetChannelVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*ChannelVideo        `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelVideosResponse) Reset() {
	*x = GetChannelVideosResponse{}
	mi := &file_video_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelVideosResponse) ProtoMessage() {}

func (x *GetChannelVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelVideosResponse.ProtoReflect.Descriptor instead.
func (*GetChannelVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_management_proto_rawDescGZIP(), []int{4}
}

func (x *GetChannelVideosResponse) GetVideos() []*ChannelVideo {
	if x != nil {
		return x.Videos
	}
	return nil
}

var File_video_management_proto protoreflect.FileDescriptor

const file_video_management_proto_rawDesc = "" +
	"\n" +
	"\x16video_management.proto\x12:com.sweetloveinyourheart.srl.videomanagement.dataproviders\"\xaa\x01\n" +
	"\x13PresignedUrlRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1f\n" +
	"\vuploader_id\x18\x04 \x01(\tR\n" +
	"uploaderId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x05 \x01(\tR\tchannelId\"u\n" +
	"\x14PresignedUrlResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\"f\n" +
	"\x17GetChannelVideosRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xd8\x01\n" +
	"\fChannelVideo\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1f\n" +
	"\vvideo_title\x18\x02 \x01(\tR\n" +
	"videoTitle\x12#\n" +
	"\rthumbnail_url\x18\x03 \x01(\tR\fthumbnailUrl\x12%\n" +
	"\x0etotal_duration\x18\x04 \x01(\x05R\rtotalDuration\x12\x1d\n" +
	"\n" +
	"total_view\x18\x05 \x01(\x03R\ttotalView\x12!\n" +
	"\fprocessed_at\x18\x06 \x01(\x03R\vprocessedAt\"|\n" +
	"\x18GetChannelVideosResponse\x12`\n" +
	"\x06videos\x18\x01 \x03(\v2H.com.sweetloveinyourheart.srl.videomanagement.dataproviders.ChannelVideoR\x06videos2\x85\x03\n" +
	"\x0fVideoManagement\x12\xb1\x01\n" +
	"\fPresignedUrl\x12O.com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlRequest\x1aP.com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlResponse\x12\xbd\x01\n" +
	"\x10GetChannelVideos\x12S.com.sweetloveinyourheart.srl.videomanagement.dataproviders.GetChannelVideosRequest\x1aT.com.sweetloveinyourheart.srl.videomanagement.dataproviders.GetChannelVideosResponseBPZNgithub.com/sweetloveinyourheart/sweet-reel/proto/code/video_management/go;grpcb\x06proto3"

var (
	file_video_management_proto_rawDescOnce sync.Once
	file_video_management_proto_rawDescData []byte
)

func file_video_management_proto_rawDescGZIP() []byte {
	file_video_management_proto_rawDescOnce.Do(func() {
		file_video_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_management_proto_rawDesc), len(file_video_management_proto_rawDesc)))
	})
	return file_video_management_proto_rawDescData
}

var file_video_management_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_video_management_proto_goTypes = []any{
	(*PresignedUrlRequest)(nil),      // 0: com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlRequest
	(*PresignedUrlResponse)(nil),     // 1: com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlResponse
	(*GetChannelVideosRequest)(nil),  // 2: com.sweetloveinyourheart.srl.videomanagement.dataproviders.GetChannelVideosRequest
	(*ChannelVideo)(nil),             // 3: com.sweetloveinyourheart.srl.videomanagement.dataproviders.ChannelVideo
	(*GetChannelVideosResponse)(nil), // 4: com.sweetloveinyourheart.srl.videomanagement.dataproviders.GetChannelVideosResponse
}
var file_video_management_proto_depIdxs = []int32{
	3, // 0: com.sweetloveinyourheart.srl.videomanagement.dataproviders.GetChannelVideosResponse.videos:type_name -> com.sweetloveinyourheart.srl.videomanagement.dataproviders.ChannelVideo
	0, // 1: com.sweetloveinyourheart.srl.videomanagement.dataproviders.VideoManagement.PresignedUrl:input_type -> com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlRequest
	2, // 2: com.sweetloveinyourheart.srl.videomanagement.dataproviders.VideoManagement.GetChannelVideos:input_type -> com.sweetloveinyourheart.srl.videomanagement.dataproviders.GetChannelVideosRequest
	1, // 3: com.sweetloveinyourheart.srl.videomanagement.dataproviders.VideoManagement.PresignedUrl:output_type -> com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlResponse
	4, // 4: com.sweetloveinyourheart.srl.videomanagement.dataproviders.VideoManagement.GetChannelVideos:output_type -> com.sweetloveinyourheart.srl.videomanagement.dataproviders.GetChannelVideosResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_video_management_proto_init() }
func file_video_management_proto_init() {
	if File_video_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_management_proto_rawDesc), len(file_video_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_management_proto_goTypes,
		DependencyIndexes: file_video_management_proto_depIdxs,
		MessageInfos:      file_video_management_proto_msgTypes,
	}.Build()
	File_video_management_proto = out.File
	file_video_management_proto_goTypes = nil
	file_video_management_proto_depIdxs = nil
}
