// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: video_management.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresignedUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignedUrlRequest) Reset() {
	*x = PresignedUrlRequest{}
	mi := &file_video_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignedUrlRequest) ProtoMessage() {}

func (x *PresignedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignedUrlRequest.ProtoReflect.Descriptor instead.
func (*PresignedUrlRequest) Descriptor() ([]byte, []int) {
	return file_video_management_proto_rawDescGZIP(), []int{0}
}

func (x *PresignedUrlRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PresignedUrlRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PresignedUrlRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type PresignedUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	PresignedUrl  string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignedUrlResponse) Reset() {
	*x = PresignedUrlResponse{}
	mi := &file_video_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignedUrlResponse) ProtoMessage() {}

func (x *PresignedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignedUrlResponse.ProtoReflect.Descriptor instead.
func (*PresignedUrlResponse) Descriptor() ([]byte, []int) {
	return file_video_management_proto_rawDescGZIP(), []int{1}
}

func (x *PresignedUrlResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *PresignedUrlResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *PresignedUrlResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_video_management_proto protoreflect.FileDescriptor

const file_video_management_proto_rawDesc = "" +
	"\n" +
	"\x16video_management.proto\x12:com.sweetloveinyourheart.srl.videomanagement.dataproviders\"j\n" +
	"\x13PresignedUrlRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"u\n" +
	"\x14PresignedUrlResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn2\xc5\x01\n" +
	"\x0fVideoManagement\x12\xb1\x01\n" +
	"\fPresignedUrl\x12O.com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlRequest\x1aP.com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlResponseBPZNgithub.com/sweetloveinyourheart/sweet-reel/proto/code/video_management/go;grpcb\x06proto3"

var (
	file_video_management_proto_rawDescOnce sync.Once
	file_video_management_proto_rawDescData []byte
)

func file_video_management_proto_rawDescGZIP() []byte {
	file_video_management_proto_rawDescOnce.Do(func() {
		file_video_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_management_proto_rawDesc), len(file_video_management_proto_rawDesc)))
	})
	return file_video_management_proto_rawDescData
}

var file_video_management_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_video_management_proto_goTypes = []any{
	(*PresignedUrlRequest)(nil),  // 0: com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlRequest
	(*PresignedUrlResponse)(nil), // 1: com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlResponse
}
var file_video_management_proto_depIdxs = []int32{
	0, // 0: com.sweetloveinyourheart.srl.videomanagement.dataproviders.VideoManagement.PresignedUrl:input_type -> com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlRequest
	1, // 1: com.sweetloveinyourheart.srl.videomanagement.dataproviders.VideoManagement.PresignedUrl:output_type -> com.sweetloveinyourheart.srl.videomanagement.dataproviders.PresignedUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_video_management_proto_init() }
func file_video_management_proto_init() {
	if File_video_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_management_proto_rawDesc), len(file_video_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_management_proto_goTypes,
		DependencyIndexes: file_video_management_proto_depIdxs,
		MessageInfos:      file_video_management_proto_msgTypes,
	}.Build()
	File_video_management_proto = out.File
	file_video_management_proto_goTypes = nil
	file_video_management_proto_depIdxs = nil
}
