// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: user.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Picture       string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpsertOAuthUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                                     // e.g. "google", "github"
	ProviderUserId string                 `protobuf:"bytes,2,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"` // ID from provider (e.g. Google sub)
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Picture        string                 `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertOAuthUserRequest) Reset() {
	*x = UpsertOAuthUserRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertOAuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertOAuthUserRequest) ProtoMessage() {}

func (x *UpsertOAuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertOAuthUserRequest.ProtoReflect.Descriptor instead.
func (*UpsertOAuthUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertOAuthUserRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UpsertOAuthUserRequest) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

func (x *UpsertOAuthUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpsertOAuthUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertOAuthUserRequest) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

type UpsertOAuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	IsNewUser     bool                   `protobuf:"varint,2,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertOAuthUserResponse) Reset() {
	*x = UpsertOAuthUserResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertOAuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertOAuthUserResponse) ProtoMessage() {}

func (x *UpsertOAuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertOAuthUserResponse.ProtoReflect.Descriptor instead.
func (*UpsertOAuthUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertOAuthUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpsertOAuthUserResponse) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type Channel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId         string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Handle          string                 `protobuf:"bytes,4,opt,name=handle,proto3" json:"handle,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	BannerUrl       string                 `protobuf:"bytes,6,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	SubscriberCount int32                  `protobuf:"varint,7,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	TotalViews      int64                  `protobuf:"varint,8,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalVideos     int32                  `protobuf:"varint,9,opt,name=total_videos,json=totalVideos,proto3" json:"total_videos,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Channel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Channel) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *Channel) GetSubscriberCount() int32 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

func (x *Channel) GetTotalViews() int64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *Channel) GetTotalVideos() int32 {
	if x != nil {
		return x.TotalVideos
	}
	return 0
}

func (x *Channel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Channel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetChannelByHandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"` // e.g., "@johndoe"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelByHandleRequest) Reset() {
	*x = GetChannelByHandleRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelByHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelByHandleRequest) ProtoMessage() {}

func (x *GetChannelByHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelByHandleRequest.ProtoReflect.Descriptor instead.
func (*GetChannelByHandleRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetChannelByHandleRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type GetChannelByHandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Owner         *User                  `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelByHandleResponse) Reset() {
	*x = GetChannelByHandleResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelByHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelByHandleResponse) ProtoMessage() {}

func (x *GetChannelByHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelByHandleResponse.ProtoReflect.Descriptor instead.
func (*GetChannelByHandleResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetChannelByHandleResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *GetChannelByHandleResponse) GetOwner() *User {
	if x != nil {
		return x.Owner
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12!com.sweetloveinyourheart.srl.user\"\x98\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xa2\x01\n" +
	"\x16UpsertOAuthUserRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\x02 \x01(\tR\x0eproviderUserId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\apicture\x18\x05 \x01(\tR\apicture\"v\n" +
	"\x17UpsertOAuthUserResponse\x12;\n" +
	"\x04user\x18\x01 \x01(\v2'.com.sweetloveinyourheart.srl.user.UserR\x04user\x12\x1e\n" +
	"\vis_new_user\x18\x02 \x01(\bR\tisNewUser\"-\n" +
	"\x12GetUserByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x13GetUserByIDResponse\x12;\n" +
	"\x04user\x18\x01 \x01(\v2'.com.sweetloveinyourheart.srl.user.UserR\x04user\"\xce\x02\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06handle\x18\x04 \x01(\tR\x06handle\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"banner_url\x18\x06 \x01(\tR\tbannerUrl\x12)\n" +
	"\x10subscriber_count\x18\a \x01(\x05R\x0fsubscriberCount\x12\x1f\n" +
	"\vtotal_views\x18\b \x01(\x03R\n" +
	"totalViews\x12!\n" +
	"\ftotal_videos\x18\t \x01(\x05R\vtotalVideos\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"3\n" +
	"\x19GetChannelByHandleRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"\xa1\x01\n" +
	"\x1aGetChannelByHandleResponse\x12D\n" +
	"\achannel\x18\x01 \x01(\v2*.com.sweetloveinyourheart.srl.user.ChannelR\achannel\x12=\n" +
	"\x05owner\x18\x02 \x01(\v2'.com.sweetloveinyourheart.srl.user.UserR\x05owner2\xaa\x03\n" +
	"\vUserService\x12\x88\x01\n" +
	"\x0fUpsertOAuthUser\x129.com.sweetloveinyourheart.srl.user.UpsertOAuthUserRequest\x1a:.com.sweetloveinyourheart.srl.user.UpsertOAuthUserResponse\x12|\n" +
	"\vGetUserByID\x125.com.sweetloveinyourheart.srl.user.GetUserByIDRequest\x1a6.com.sweetloveinyourheart.srl.user.GetUserByIDResponse\x12\x91\x01\n" +
	"\x12GetChannelByHandle\x12<.com.sweetloveinyourheart.srl.user.GetChannelByHandleRequest\x1a=.com.sweetloveinyourheart.srl.user.GetChannelByHandleResponseBDZBgithub.com/sweetloveinyourheart/sweet-reel/proto/code/user/go;grpcb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_proto_goTypes = []any{
	(*User)(nil),                       // 0: com.sweetloveinyourheart.srl.user.User
	(*UpsertOAuthUserRequest)(nil),     // 1: com.sweetloveinyourheart.srl.user.UpsertOAuthUserRequest
	(*UpsertOAuthUserResponse)(nil),    // 2: com.sweetloveinyourheart.srl.user.UpsertOAuthUserResponse
	(*GetUserByIDRequest)(nil),         // 3: com.sweetloveinyourheart.srl.user.GetUserByIDRequest
	(*GetUserByIDResponse)(nil),        // 4: com.sweetloveinyourheart.srl.user.GetUserByIDResponse
	(*Channel)(nil),                    // 5: com.sweetloveinyourheart.srl.user.Channel
	(*GetChannelByHandleRequest)(nil),  // 6: com.sweetloveinyourheart.srl.user.GetChannelByHandleRequest
	(*GetChannelByHandleResponse)(nil), // 7: com.sweetloveinyourheart.srl.user.GetChannelByHandleResponse
}
var file_user_proto_depIdxs = []int32{
	0, // 0: com.sweetloveinyourheart.srl.user.UpsertOAuthUserResponse.user:type_name -> com.sweetloveinyourheart.srl.user.User
	0, // 1: com.sweetloveinyourheart.srl.user.GetUserByIDResponse.user:type_name -> com.sweetloveinyourheart.srl.user.User
	5, // 2: com.sweetloveinyourheart.srl.user.GetChannelByHandleResponse.channel:type_name -> com.sweetloveinyourheart.srl.user.Channel
	0, // 3: com.sweetloveinyourheart.srl.user.GetChannelByHandleResponse.owner:type_name -> com.sweetloveinyourheart.srl.user.User
	1, // 4: com.sweetloveinyourheart.srl.user.UserService.UpsertOAuthUser:input_type -> com.sweetloveinyourheart.srl.user.UpsertOAuthUserRequest
	3, // 5: com.sweetloveinyourheart.srl.user.UserService.GetUserByID:input_type -> com.sweetloveinyourheart.srl.user.GetUserByIDRequest
	6, // 6: com.sweetloveinyourheart.srl.user.UserService.GetChannelByHandle:input_type -> com.sweetloveinyourheart.srl.user.GetChannelByHandleRequest
	2, // 7: com.sweetloveinyourheart.srl.user.UserService.UpsertOAuthUser:output_type -> com.sweetloveinyourheart.srl.user.UpsertOAuthUserResponse
	4, // 8: com.sweetloveinyourheart.srl.user.UserService.GetUserByID:output_type -> com.sweetloveinyourheart.srl.user.GetUserByIDResponse
	7, // 9: com.sweetloveinyourheart.srl.user.UserService.GetChannelByHandle:output_type -> com.sweetloveinyourheart.srl.user.GetChannelByHandleResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
